name: MoonGenerator
version: ${project.version}
main: me.shoko.moongenerator.mainMoonGenerator
api-version: 1.13
authors: [Shoko]
description: The best moon generator plugin for mc 1.13.2
website: https://www.spigotmc.org/members/shoko.633572/
commands:
  moon:
    description: Generates or Load the moon world
    usage: /moon