name: MoonGenerator
version: 2
main: me.shoko.moongenerator.mainMoonGenerator
api-version: 1.14
authors: [Shoko]
description: The best moon generator plugin for mc 1.14.4
website: https://www.spigotmc.org/members/shoko.633572/