name: MoonGenerator
version: 1.1
main: me.shoko.moongenerator.mainMoonGenerator
api-version: 1.13
authors: [Shoko]
description: The best moon generator plugin for mc 1.13.2
website: http://www.deadhuntercc.fluctis.com/
